eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: ta-data-access

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
#    connection:
#      release_mode: after_statement
#      release-mode: after-statement

datasource:
  main:
    jdbc-url: jdbc:mysql://localhost:13306/testdb?useUnicode=true&characterEncoding=UTF-8
    username: proxy
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: false
    release-mode: after-statement
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  read1:
    jdbc-url: jdbc:mysql://localhost:13307/testdb?useUnicode=true&characterEncoding=UTF-8
    username: proxy
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: false
    release-mode: after-statement
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  read2:
    jdbc-url: jdbc:mysql://localhost:13308/testdb?useUnicode=true&characterEncoding=UTF-8
    username: proxy
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: false
    release-mode: after-statement
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
